# Kubernetes Namespace Configuration
# Creates isolated environments for different deployment stages

apiVersion: v1
kind: Namespace
metadata:
  name: micro-learning-scheduler-development
  labels:
    app: micro-learning-scheduler
    environment: development
    version: v1
  annotations:
    description: "Development environment for Micro-Learning Scheduler"
    contact: "dev-team@micro-learning-scheduler.com"
    created-by: "deployment-automation"

---
apiVersion: v1
kind: Namespace
metadata:
  name: micro-learning-scheduler-staging
  labels:
    app: micro-learning-scheduler
    environment: staging
    version: v1
  annotations:
    description: "Staging environment for Micro-Learning Scheduler"
    contact: "dev-team@micro-learning-scheduler.com"
    created-by: "deployment-automation"

---
apiVersion: v1
kind: Namespace
metadata:
  name: micro-learning-scheduler-production
  labels:
    app: micro-learning-scheduler
    environment: production
    version: v1
  annotations:
    description: "Production environment for Micro-Learning Scheduler"
    contact: "ops-team@micro-learning-scheduler.com"
    created-by: "deployment-automation"

---
# Resource Quotas for each environment
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: micro-learning-scheduler-development
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    persistentvolumeclaims: "4"
    services: "5"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: micro-learning-scheduler-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "8"
    services: "10"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: micro-learning-scheduler-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    persistentvolumeclaims: "20"
    services: "20"

---
# Network Policies for security isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: micro-learning-scheduler-development
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: micro-learning-scheduler-staging
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: micro-learning-scheduler-production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# Allow internal communication within namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: micro-learning-scheduler-development
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-development
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-development

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: micro-learning-scheduler-staging
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-staging
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-staging

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: micro-learning-scheduler-production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-production
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: micro-learning-scheduler-production
