# Kubernetes Secrets Configuration
# Sensitive data for different environments
# Note: In production, these should be managed by external secret management systems

# Development Environment Secrets
apiVersion: v1
kind: Secret
metadata:
  name: micro-learning-scheduler-secrets
  namespace: micro-learning-scheduler-development
  labels:
    app: micro-learning-scheduler
    environment: development
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: ZGV2X3VzZXI=  # dev_user
  DB_PASSWORD: ZGV2X3Bhc3N3b3Jk  # dev_password
  
  # Redis password
  REDIS_PASSWORD: ZGV2X3JlZGlzX3Bhc3M=  # dev_redis_pass
  
  # JWT Secret
  JWT_SECRET: ZGV2X2p3dF9zZWNyZXRfa2V5XzEyMw==  # dev_jwt_secret_key_123
  
  # Session Secret
  SESSION_SECRET: ZGV2X3Nlc3Npb25fc2VjcmV0XzQ1Ng==  # dev_session_secret_456
  
  # n8n credentials
  N8N_USER_MANAGEMENT_JWT_SECRET: ZGV2X244bl9qd3Rfc2VjcmV0  # dev_n8n_jwt_secret
  N8N_ENCRYPTION_KEY: ZGV2X244bl9lbmNyeXB0aW9uX2tleQ==  # dev_n8n_encryption_key
  
  # API Keys (development/testing)
  OPENAI_API_KEY: c2tfZGV2X29wZW5haV9hcGlfa2V5  # sk-dev_openai_api_key
  SENDGRID_API_KEY: ZGV2X3NlbmRncmlkX2FwaV9rZXk=  # dev_sendgrid_api_key
  SLACK_BOT_TOKEN: eG94Yi1kZXZfc2xhY2tfYm90X3Rva2Vu  # xoxb-dev_slack_bot_token
  GOOGLE_CALENDAR_API_KEY: ZGV2X2dvb2dsZV9jYWxlbmRhcl9hcGlfa2V5  # dev_google_calendar_api_key

---
# Staging Environment Secrets
apiVersion: v1
kind: Secret
metadata:
  name: micro-learning-scheduler-secrets
  namespace: micro-learning-scheduler-staging
  labels:
    app: micro-learning-scheduler
    environment: staging
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: c3RhZ2luZ191c2Vy  # staging_user
  DB_PASSWORD: c3RhZ2luZ19wYXNzd29yZF8xMjM=  # staging_password_123
  
  # Redis password
  REDIS_PASSWORD: c3RhZ2luZ19yZWRpc19wYXNzXzQ1Ng==  # staging_redis_pass_456
  
  # JWT Secret
  JWT_SECRET: c3RhZ2luZ19qd3Rfc2VjcmV0X2tleV83ODk=  # staging_jwt_secret_key_789
  
  # Session Secret
  SESSION_SECRET: c3RhZ2luZ19zZXNzaW9uX3NlY3JldF8xMjM=  # staging_session_secret_123
  
  # n8n credentials
  N8N_USER_MANAGEMENT_JWT_SECRET: c3RhZ2luZ19uOG5fand0X3NlY3JldA==  # staging_n8n_jwt_secret
  N8N_ENCRYPTION_KEY: c3RhZ2luZ19uOG5fZW5jcnlwdGlvbl9rZXk=  # staging_n8n_encryption_key
  
  # API Keys (staging)
  OPENAI_API_KEY: c2tfc3RhZ2luZ19vcGVuYWlfYXBpX2tleQ==  # sk-staging_openai_api_key
  SENDGRID_API_KEY: c3RhZ2luZ19zZW5kZ3JpZF9hcGlfa2V5  # staging_sendgrid_api_key
  SLACK_BOT_TOKEN: eG94Yi1zdGFnaW5nX3NsYWNrX2JvdF90b2tlbg==  # xoxb-staging_slack_bot_token
  GOOGLE_CALENDAR_API_KEY: c3RhZ2luZ19nb29nbGVfY2FsZW5kYXJfYXBpX2tleQ==  # staging_google_calendar_api_key

---
# Production Environment Secrets
apiVersion: v1
kind: Secret
metadata:
  name: micro-learning-scheduler-secrets
  namespace: micro-learning-scheduler-production
  labels:
    app: micro-learning-scheduler
    environment: production
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # IMPORTANT: These should be replaced with actual production values
  DB_USERNAME: cHJvZF91c2Vy  # prod_user
  DB_PASSWORD: cHJvZF9zdXBlcl9zZWN1cmVfcGFzc3dvcmRfMTIzNDU=  # prod_super_secure_password_12345
  
  # Redis password
  REDIS_PASSWORD: cHJvZF9yZWRpc19zdXBlcl9zZWN1cmVfcGFzcw==  # prod_redis_super_secure_pass
  
  # JWT Secret
  JWT_SECRET: cHJvZF9qd3Rfc3VwZXJfc2VjdXJlX2tleV85ODc2NTQzMjE=  # prod_jwt_super_secure_key_987654321
  
  # Session Secret
  SESSION_SECRET: cHJvZF9zZXNzaW9uX3N1cGVyX3NlY3VyZV9rZXlfNDU2Nzg5  # prod_session_super_secure_key_456789
  
  # n8n credentials
  N8N_USER_MANAGEMENT_JWT_SECRET: cHJvZF9uOG5fand0X3N1cGVyX3NlY3VyZV9rZXk=  # prod_n8n_jwt_super_secure_key
  N8N_ENCRYPTION_KEY: cHJvZF9uOG5fZW5jcnlwdGlvbl9zdXBlcl9zZWN1cmVfa2V5  # prod_n8n_encryption_super_secure_key
  
  # API Keys (production)
  # IMPORTANT: Replace with actual production API keys
  OPENAI_API_KEY: c2tfcHJvZF9vcGVuYWlfYXBpX2tleQ==  # sk-prod_openai_api_key
  SENDGRID_API_KEY: cHJvZF9zZW5kZ3JpZF9hcGlfa2V5  # prod_sendgrid_api_key
  SLACK_BOT_TOKEN: eG94Yi1wcm9kX3NsYWNrX2JvdF90b2tlbg==  # xoxb-prod_slack_bot_token
  GOOGLE_CALENDAR_API_KEY: cHJvZF9nb29nbGVfY2FsZW5kYXJfYXBpX2tleQ==  # prod_google_calendar_api_key
  
  # Additional production secrets
  WEBHOOK_SECRET: cHJvZF93ZWJob29rX3NlY3JldF9rZXk=  # prod_webhook_secret_key
  ENCRYPTION_KEY: cHJvZF9lbmNyeXB0aW9uX21hc3Rlcl9rZXk=  # prod_encryption_master_key

---
# TLS Secrets for HTTPS (staging)
apiVersion: v1
kind: Secret
metadata:
  name: tls-staging-cert
  namespace: micro-learning-scheduler-staging
  labels:
    app: micro-learning-scheduler
    environment: staging
    component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # staging certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # staging private key

---
# TLS Secrets for HTTPS (production)
apiVersion: v1
kind: Secret
metadata:
  name: tls-production-cert
  namespace: micro-learning-scheduler-production
  labels:
    app: micro-learning-scheduler
    environment: production
    component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # production certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # production private key

---
# Docker Registry Secret (for private image pulls)
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: micro-learning-scheduler-staging
  labels:
    app: micro-learning-scheduler
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: micro-learning-scheduler-production
  labels:
    app: micro-learning-scheduler
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
